<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flt-semanticsflt-semantic-node-Apply Deals</name>
   <tag></tag>
   <elementGuidId>627158d2-2eab-4906-b17e-16696054145e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//flt-semantics[@id='flt-semantic-node-40']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flt-semantic-node-40</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>flt-semantics</value>
      <webElementGuid>4dcee6cb-b8ad-4069-8ab7-2508f68f4039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flt-semantic-node-40</value>
      <webElementGuid>8155cfdb-11ac-4e93-91d4-96ff72571863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e4629bc9-0f7d-4934-972c-0f6e318b2323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>92acea48-3dd8-4aac-89f4-a23d7bd48bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Apply Deal</value>
      <webElementGuid>f333ab5b-be15-4ee9-a584-77b3e4fa75f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flt-semantic-node-40&quot;)</value>
      <webElementGuid>404bd0b6-380b-40b1-b1fa-746b0613f98c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-40']</value>
      <webElementGuid>b8232b62-0970-4324-aa1d-c7c6cf57bc15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-39']/flt-semantics-container/flt-semantics</value>
      <webElementGuid>94669935-47cb-487c-9e95-bb433b8a4144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flt-semantics[32]/flt-semantics-container/flt-semantics/flt-semantics-container/flt-semantics/flt-semantics-container/flt-semantics/flt-semantics-container/flt-semantics/flt-semantics-container/flt-semantics/flt-semantics-container/flt-semantics</value>
      <webElementGuid>42b6dde6-8978-4ec4-aa32-9e5e3f812ed9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
