<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Stay 7, Pay 5 on SitesStay 7, Pay 5 on _a66c36</name>
   <tag></tag>
   <elementGuidId>0c596577-07ef-475d-ac2d-5432e5b113ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d1ec3258-e743-412b-ab87-9c2bde2f379e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>24ec47f1-f2ec-4f99-b4b7-944466464b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>dd70748c-aaab-4da0-949e-02c865e56d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×Stay 7, Pay 5 on Sites!Stay 7, Pay 5 on Sites!Promo Code ConditionsAll of these conditions must match for the codeBooking Period9 Oct 2023 - 21 Jun 2024Stay Dates10 Oct 2023 - 27 Jun 2024Night Stay RangeMaximum 28 DaysCheck-In DaysAny day in the weekAdditional InformationDiscounted rate does not apply to blockout dates between 02 Nov 2023 and 07 Nov 2023.Cannot be used in conjunction with G'Day membership discount.Full terms and conditions: Offer valid from 09 Oct 2023 to 21 Jun 2024. Cannot be used in conjunction with any other offer. Must enter promo code at time of booking. Please note that blackout dates may apply. Offer valid for online bookings. Discount is based on the standard rate. Subject to availability at time of booking.</value>
      <webElementGuid>abd095e5-28ca-42a8-b4e6-30f11eb6de95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal&quot;)</value>
      <webElementGuid>e80972af-a78b-4098-8608-c5a6ed645645</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='modal']</value>
      <webElementGuid>75f8a6d3-bfce-4d50-933b-09d3d63ab252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>22e054bc-6f88-42fd-8460-1fb78c011015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;×Stay 7, Pay 5 on Sites!Stay 7, Pay 5 on Sites!Promo Code ConditionsAll of these conditions must match for the codeBooking Period9 Oct 2023 - 21 Jun 2024Stay Dates10 Oct 2023 - 27 Jun 2024Night Stay RangeMaximum 28 DaysCheck-In DaysAny day in the weekAdditional InformationDiscounted rate does not apply to blockout dates between 02 Nov 2023 and 07 Nov 2023.Cannot be used in conjunction with G&quot; , &quot;'&quot; , &quot;Day membership discount.Full terms and conditions: Offer valid from 09 Oct 2023 to 21 Jun 2024. Cannot be used in conjunction with any other offer. Must enter promo code at time of booking. Please note that blackout dates may apply. Offer valid for online bookings. Discount is based on the standard rate. Subject to availability at time of booking.&quot;) or . = concat(&quot;×Stay 7, Pay 5 on Sites!Stay 7, Pay 5 on Sites!Promo Code ConditionsAll of these conditions must match for the codeBooking Period9 Oct 2023 - 21 Jun 2024Stay Dates10 Oct 2023 - 27 Jun 2024Night Stay RangeMaximum 28 DaysCheck-In DaysAny day in the weekAdditional InformationDiscounted rate does not apply to blockout dates between 02 Nov 2023 and 07 Nov 2023.Cannot be used in conjunction with G&quot; , &quot;'&quot; , &quot;Day membership discount.Full terms and conditions: Offer valid from 09 Oct 2023 to 21 Jun 2024. Cannot be used in conjunction with any other offer. Must enter promo code at time of booking. Please note that blackout dates may apply. Offer valid for online bookings. Discount is based on the standard rate. Subject to availability at time of booking.&quot;))]</value>
      <webElementGuid>cf0ec9b5-ded1-4741-afdf-26418be6d41c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
