<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flt-semanticsflt-semantic-node-SeeAndDoText</name>
   <tag></tag>
   <elementGuidId>cd0efd45-dd99-4e35-8073-901b36185de7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//flt-semantics[@id='flt-semantic-node-25']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flt-semantic-node-25</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>flt-semantics</value>
      <webElementGuid>a464cff7-8b94-4d9e-a248-79d4fad1a988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flt-semantic-node-25</value>
      <webElementGuid>e32e41a0-476b-46a4-901b-acaea559170a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>See &amp; Do</value>
      <webElementGuid>cccbfd33-d8ab-4e8e-9498-5188d849ddfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>facf0eab-a19a-4391-8b3d-02810aeb40ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flt-semantic-node-25&quot;)</value>
      <webElementGuid>97d3c12a-e56d-43d5-aa42-6b4221c96fb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-25']</value>
      <webElementGuid>3850c0c4-3d43-4874-83c8-6c3a0f2c10ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-4']/flt-semantics-container/flt-semantics[6]</value>
      <webElementGuid>6fe6933c-0f63-4bf3-bb00-daa16d2fc94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flt-semantics[6]</value>
      <webElementGuid>3a8e7449-5d07-4908-9002-1f2983e8e4d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
