<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flt-semanticsflt-semantic-node-parkInfo</name>
   <tag></tag>
   <elementGuidId>bd345e40-592d-4496-9c7b-430cd6187293</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//flt-semantics[@id='flt-semantic-node-10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flt-semantic-node-10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>flt-semantics</value>
      <webElementGuid>3488294f-f1de-4028-96ba-7eea065eb1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flt-semantic-node-10</value>
      <webElementGuid>f4a10a86-813e-4b3e-ad43-3f563ad5ca34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9e277fe7-9ee4-47dc-9832-d435622f0fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Park Info</value>
      <webElementGuid>72dd00b9-951a-486b-984b-e1d47c6c34a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f08f973-9177-4520-a5cb-934b3000a05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flt-semantic-node-10&quot;)</value>
      <webElementGuid>c02156cc-50ec-47b2-b33b-1823961a7268</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-10']</value>
      <webElementGuid>dadd9799-3f73-4de7-a004-b4b4c0f709ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-8']/flt-semantics-container/flt-semantics[2]</value>
      <webElementGuid>1b09bd48-de63-4f29-8d99-8c44a98730cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flt-semantics[5]/flt-semantics-container/flt-semantics[2]</value>
      <webElementGuid>5589eb76-c28e-436e-8c74-63b046b8bbcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
