<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flt-semanticsflt-semantic-node-RemoveDeals</name>
   <tag></tag>
   <elementGuidId>ca831821-3f36-4bf8-be49-8f8b3ecba6a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//flt-semantics[@id='flt-semantic-node-16']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flt-semantic-node-16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>flt-semantics</value>
      <webElementGuid>f59adf4b-c97d-4b4c-8b00-7f7f50bfed2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flt-semantic-node-16</value>
      <webElementGuid>1bbadeb1-a5d5-492d-8ebd-24373d348d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>afba2697-024f-449c-ac4f-52697f1c5d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>77d63191-b9aa-4321-945b-5a79a0834235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Remove Deal</value>
      <webElementGuid>700a8121-5e29-4f4d-b878-f7f862482fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flt-semantic-node-16&quot;)</value>
      <webElementGuid>ed49ff53-32dd-4a26-b9db-8632d7723fdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-16']</value>
      <webElementGuid>2d5d67ea-0ea4-43a4-96cf-c75c46891e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-15']/flt-semantics-container/flt-semantics</value>
      <webElementGuid>ed69ee8f-d835-43da-9c4e-7a79e8ddf436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flt-semantics[6]/flt-semantics-container/flt-semantics/flt-semantics-container/flt-semantics/flt-semantics-container/flt-semantics</value>
      <webElementGuid>344a3f7f-741f-49e6-9fe9-d61008602b99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
