<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flt-semanticsflt-semantic-node-ParkInfoText</name>
   <tag></tag>
   <elementGuidId>77f01696-bea1-4185-8a05-e97ae8896b85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//flt-semantics[@id='flt-semantic-node-24']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flt-semantic-node-24</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>flt-semantics</value>
      <webElementGuid>7af5bd87-644d-452b-b15b-048eda08d775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flt-semantic-node-24</value>
      <webElementGuid>cffa95b3-aa70-4081-bc23-8718164d80c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Park Info</value>
      <webElementGuid>0cff9607-2855-411e-b5b1-49794376e609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>180aa323-b11b-4024-86c5-0efab96ac89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flt-semantic-node-24&quot;)</value>
      <webElementGuid>5e58b1a2-6d34-413b-9b46-30bb51c75550</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-24']</value>
      <webElementGuid>0fd72605-61c9-4967-a4a7-8b3067216be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-4']/flt-semantics-container/flt-semantics[6]</value>
      <webElementGuid>a8dd9df2-f3fe-4a4e-8565-f1c379672c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flt-semantics[6]</value>
      <webElementGuid>89cc77bc-a0c4-4dd5-8682-18f1e31e1c5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
