<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flt-semanticsflt-semantic-node-see and do</name>
   <tag></tag>
   <elementGuidId>bcea1226-2eef-4028-84ec-d216ac6adee8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//flt-semantics[@id='flt-semantic-node-11']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flt-semantic-node-11</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>flt-semantics</value>
      <webElementGuid>61bff62f-762c-4809-b532-a4df20aa54c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flt-semantic-node-11</value>
      <webElementGuid>90f03646-c8c9-481f-819a-912743f6b020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cf1016dd-17b8-44c9-a603-aa88a4261dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>See &amp; Do
Tab 3 of 5</value>
      <webElementGuid>2cd708ad-a879-4cca-abfc-79bd1e3f8a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f5624224-7d53-49c6-8e95-bc384cf73af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flt-semantic-node-11&quot;)</value>
      <webElementGuid>dbc37528-25f3-4983-804a-a68d530b5514</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-11']</value>
      <webElementGuid>09e53adb-2593-4818-9d19-4e8ac82c1ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-8']/flt-semantics-container/flt-semantics[3]</value>
      <webElementGuid>4e8f8f00-f6e0-4069-8ff0-8eb4fb46e811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flt-semantics[5]/flt-semantics-container/flt-semantics[3]</value>
      <webElementGuid>acc51bc3-ed20-4ba1-9d6e-0d28c0daea8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
