<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flutter-view</name>
   <tag></tag>
   <elementGuidId>e8999a6d-c09c-4211-9033-c8a888515036</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flutter_target']/flutter-view</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>flutter-view</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>flutter-view</value>
      <webElementGuid>14c42013-cd46-4482-8a42-53248401a13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flutter_target&quot;)/flutter-view[1]</value>
      <webElementGuid>ed8cae02-8519-451e-98b8-c63580d289b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flutter_target']/flutter-view</value>
      <webElementGuid>f22bd4c4-e38b-4c44-825b-18e74ad7a41a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flutter-view</value>
      <webElementGuid>c28fb2af-c1e5-4eee-8d09-9a9d12d8762e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
